env:
  EXAMPLES_BRANCH: ${{ inputs.examplesRepoBranch || 'development' }}
  EXAMPLES_REPO: ${{ inputs.examplesRepo || 'apache/activemq-artemis-examples' }}
jobs:
  checks:
    name: Checks (${{ matrix.java }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: activemq-artemis
    - continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      name: Cache Maven Local Repo
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mvn-${{ hashFiles('activemq-artemis/**/pom.xml') }}
        path: '~/.m2/repository/

          '
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Checkout Artemis Examples Repo
      uses: actions/checkout@v4
      with:
        path: activemq-artemis-examples
        ref: ${{ env.EXAMPLES_BRANCH }}
        repository: ${{ env.EXAMPLES_REPO }}
    - continue-on-error: true
      name: Build Main
      run: 'cd activemq-artemis

        mvn -s .github/maven-settings.xml -DskipTests -Derrorprone -Pdev -Pjmh install

        '
    - continue-on-error: true
      name: Set Examples Version to Artemis Version
      run: 'cd activemq-artemis

        CURRENT_ARTEMIS_BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version
        -q -DforceStdout)

        echo "Current Artemis version: ${CURRENT_ARTEMIS_BUILD_VERSION}"

        cd ../activemq-artemis-examples

        ./scripts/update-examples-version.sh ${CURRENT_ARTEMIS_BUILD_VERSION}

        '
    - continue-on-error: true
      if: matrix.java == '11'
      name: Build Examples (JDK11 / -Prelease)
      run: 'cd activemq-artemis-examples

        mvn -s ../activemq-artemis/.github/maven-settings.xml install -Prelease

        '
    - continue-on-error: true
      if: matrix.java != '11'
      name: Build Examples (JDK >11 / -Pexamples,noRun)
      run: 'cd activemq-artemis-examples

        mvn -s ../activemq-artemis/.github/maven-settings.xml install -Pexamples,noRun

        '
    - continue-on-error: true
      if: matrix.java == '11'
      name: Javadoc Check (JDK11 / -Prelease)
      run: 'cd activemq-artemis

        mvn -s .github/maven-settings.xml javadoc:javadoc -Prelease -DskipWebsiteDocGeneration=true
        -DskipWebsiteJavadocGeneration=true

        '
    - continue-on-error: true
      if: matrix.java != '11'
      name: Javadoc Check (JDK >11)
      run: 'cd activemq-artemis

        mvn -s .github/maven-settings.xml javadoc:javadoc

        '
    - continue-on-error: true
      if: matrix.java == '11'
      name: Website Content Check (JDK11 only / -Prelease)
      run: 'cd activemq-artemis

        mvn -s .github/maven-settings.xml clean install -DskipTests -Prelease -am
        -pl "artemis-website"

        '
    - continue-on-error: true
      name: Clean Up Before Caching
      run: 'rm -rf ~/.m2/repository/org/apache/activemq/tests

        rm -rf ~/.m2/repository/org/apache/activemq/examples

        if [ -d ~/.m2/repository/org/apache/activemq ]; then find ~/.m2/repository/org/apache/activemq
        -name "*-SNAPSHOT" -type d -prune -exec rm -r ''{}'' \; ; fi

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
  test:
    name: Test (${{ matrix.java }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: activemq-artemis
    - continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      name: Cache Maven Local Repo
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mvn-${{ hashFiles('activemq-artemis/**/pom.xml') }}
        path: '~/.m2/repository/

          '
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Fast Tests
      run: 'cd activemq-artemis

        mvn -s .github/maven-settings.xml -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull
        -Pfast-tests -Pcompatibility-tests install

        '
    - continue-on-error: true
      name: Clean Up Before Caching
      run: 'rm -rf ~/.m2/repository/org/apache/activemq/tests

        rm -rf ~/.m2/repository/org/apache/activemq/examples

        if [ -d ~/.m2/repository/org/apache/activemq ]; then find ~/.m2/repository/org/apache/activemq
        -name "*-SNAPSHOT" -type d -prune -exec rm -r ''{}'' \; ; fi

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
